### ISSUE TITLE
Not able to load tmTheme file

### ISSUE THREAD

**Issue by jpporta** [krivahtoo/silicon.nvim#47]
![image](https://github.com/krivahtoo/silicon.nvim/assets/23032080/6bf12260-a25d-482b-a34f-9b394082bf1d)

![image](https://github.com/krivahtoo/silicon.nvim/assets/23032080/e7295952-704e-4ec6-8040-8ae6ece63345)

Am I missing something to import the custom theme file

**Comment by krivahtoo** [comment]
`silicon.nvim` currently does not support loading themes from file.

**Comment by confusedkernel** [comment]
Hello! I was wondering if this issue was eventually fixed? Because I'm also trying to load a theme from file but couldn't. The theme file is there, but it just says 'could not load'

**Edit:** the custom theme was catppuccin mocha from their [bat fork](https://github.com/catppuccin/bat/blob/699f60fc8ec434574ca7451b444b880430319941/themes/Catppuccin%20Mocha.tmTheme#L4)

<img width="1082" alt="Screenshot 2024-12-29 at 13 41 08" src="https://github.com/user-attachments/assets/868ad628-a2bf-4dfb-a93e-851a70f1b472" />

NEOVIM 0.10.2

**Comment by krivahtoo** [comment]
Themes can't be loaded from an absolute path yet.

To load the theme, you have to copy the theme file to the `themes` folder in the configuration folder (You can check with `:= require('silicon').config_path()`). Then, you can rebuild themes with `:= require('silicon').rebuild_themes()`. The theme should be available for use. You check all themes with `:= require('silicon').list_themes()`
